### ISSUE TITLE
witam nie dziala

### ISSUE THREAD

**Issue by mlodyskiny** [7ez/osl-frontend#3]
hello this is the paste police please stop pasting

**Comment by 7ez** [comment]
zazdroscisz mi bo frontend umiem a ty nie
![caption](https://github.com/user-attachments/assets/62f5f896-6ba9-4a9d-8c84-1cf2c3a0f97d)

**Comment by mlodyskiny** [comment]
XDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
